version: '3'
services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend-ui
    ports:
      - "8080:80"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
