backend:
  image:
    repository: your-dockerhub-user/backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 5000
    nodePort: 30090

frontend:
  image:
    repository: your-dockerhub-user/frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 80
    nodePort: 30091
