global:
  scrape_interval: 15s  # Mỗi 15 giây Prometheus sẽ scrape dữ liệu

scrape_configs:
  - job_name: 'flask-backend'
    static_configs:
      - targets: ['backend:5001']  # 'backend' là tên service trong docker-compose
